import type { Metadata } from "next";
import "./globals.css";
import { PageLayout } from "@/components/page-layout";
// import SmoothScroll from "@/components/lenis-smooth-scroll";
import localFont from "next/font/local";
import SmoothScroll from "@/components/lenis-smooth-scroll";


const trap = localFont({
  src: "./fonts/trap/Trap-Regular.otf",
  variable: "--font-trap",
});


const hkGrotesk = localFont({
  src: [
    {
      path: "./fonts/hk-grotesk/HKGrotesk-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/hk-grotesk/HKGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/hk-grotesk/HKGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/hk-grotesk/HKGrotesk-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/hk-grotesk/HKGrotesk-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});


export const metadata: Metadata = {
  title: "Subsidized Energy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hkGrotesk.className} ${trap.variable} antialiased`}>
        <SmoothScroll>
          <PageLayout>{children}</PageLayout>
        </SmoothScroll>
      </body>
    </html>
  );
}
